CREATE TABLE "UserInfo" (
	"U_CD"	NUMBER		NOT NULL,
	"U_ID"	VARCHAR2(100)		NOT NULL,
	"U_PW"	VARCHAR2(200)		NOT NULL,
	"U_NM"	VARCHAR2(200)		NOT NULL,
	"U_NUM"	VARCHAR2(200)		NOT NULL,
	"U_IDENTY"	NUMBER		NOT NULL,
	"USER_EMAIL"	VARCHAR2(200)		NOT NULL,
	"U_ADDRE"	VARCHAR2(500)		NULL,
	"SYS_JOIN"	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	"BIRTH_DATE"	TIMESTAMP		NOT NULL,
	"ROLE_CD"	INTEGER		NOT NULL
);

COMMENT ON COLUMN "UserInfo"."U_CD" IS '회원식별번호';

COMMENT ON COLUMN "UserInfo"."END_DATE" IS '최종접속일이 4개월 전이면 휴면전환';

CREATE TABLE "user_kko" (
	"TOKEN"	VARCHAR(255)		NOT NULL,
	"K_EMIAL"	VARCHAR(255)		NULL,
	"K_BIRTH"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "user_kko"."TOKEN" IS 'api로 가져올 토큰';

CREATE TABLE "BOARD" (
	"POST_CD"	NUMBER		NOT NULL,
	"U_CD"	NUMBER		NOT NULL,
	"POST_TITLE"	VARCHAR2(500)		NULL,
	"POST_CONTENT"	CLOB		NULL,
	"POST_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"POST_STAT"	NUMBER		NOT NULL,
	"REP_CD"	VARCHAR(255)		NOT NULL
);

COMMENT ON COLUMN "BOARD"."U_CD" IS '회원식별번호';

CREATE TABLE "AUTHORITY" (
	"ROLE_CD"	INTEGER		NOT NULL,
	"ROLE_NM"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "AUTHORITY"."ROLE_NM" IS '관리자/멤버/에이스/프리미어';

CREATE TABLE "TRANSACTION" (
	"TRANS_NO"	VARCHAR(255)		NOT NULL,
	"ACC_NO"	VARCHAR2(100)		NOT NULL,
	"TRANS_INPUT"	VARCHAR(255)		NOT NULL,
	"RECIEVER"	VARCHAR(255)		NOT NULL,
	"TRAN_TYPE"	VARCHAR(255)		NOT NULL,
	"TRAN_DATE"	VARCHAR(255)		NOT NULL,
	"TRAN_MN"	VARCHAR(255)		NULL,
	"TRAN_BAL"	VARCHAR(255)		NULL,
	"BANK_CD"	NUMBER		NOT NULL
);

CREATE TABLE "BANK_TYPE" (
	"BANK_CD"	NUMBER		NOT NULL,
	"BANK_NM"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "BANK_TYPE"."BANK_NM" IS '유니크로 만들어야할 것?';

CREATE TABLE "ACCOUNT_INFO" (
	"ACC_NO"	VARCHAR2(100)		NOT NULL,
	"U_CD"	       NUMBER		NOT NULL,
	"PRO_CD"	VARCHAR(255)		NOT NULL,
	"ACC_NM"	VARCHAR2(100)		NOT NULL,
	"ACC_PW"	NUMBER		NOT NULL,
	"ACC_BAL"	NUMBER		NOT NULL,
	"ACC_DATE"	TIMESTAMP		NOT NULL,
	"ACC_CON"	CHAR(1)	DEFAULT	NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "ACCOUNT_INFO"."U_CD" IS '회원식별번호';

COMMENT ON COLUMN "ACCOUNT_INFO"."ACC_CON" IS 'Y/N으로 구분';

CREATE TABLE "PRODUCT" (
	"PRO_CD"	VARCHAR(255)		NOT NULL,
	"PRO_NM"	VARCHAR(255)		NULL,
	"PRO_TYPE"	VARCHAR(255)		NULL
);

CREATE TABLE "REPLY" (
	"REP_CD"	VARCHAR(255)		NOT NULL,
	"REP_CONTENT"	VARCHAR2(1000)	DEFAULT '현재 문의량이 많아 답변이 지연되고 있습니다. 최대한 빠르게 응대하고 있사오니 잠시만 기다려주세요.'	NULL,
	"U_CD"	       NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."U_CD" IS '회원식별번호';

CREATE TABLE "RESTINPEACE" (
	"U_CD"	       NUMBER		NOT NULL,
	"U_STAT"	VARCHAR(255)		NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "RESTINPEACE"."U_CD" IS '회원식별번호';

COMMENT ON COLUMN "RESTINPEACE"."U_STAT" IS '휴면/탈퇴 :';

ALTER TABLE "UserInfo" ADD CONSTRAINT "PK_USERINFO" PRIMARY KEY (
	"U_CD"
);

ALTER TABLE "user_kko" ADD CONSTRAINT "PK_USER_KKO" PRIMARY KEY (
	"TOKEN"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"POST_CD"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"ROLE_CD"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "PK_TRANSACTION" PRIMARY KEY (
	"TRANS_NO",
	"ACC_NO"
);

ALTER TABLE "BANK_TYPE" ADD CONSTRAINT "PK_BANK_TYPE" PRIMARY KEY (
	"BANK_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "PK_ACCOUNT_INFO" PRIMARY KEY (
	"ACC_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_CD"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REP_CD"
);

ALTER TABLE "RESTINPEACE" ADD CONSTRAINT "PK_RESTINPEACE" PRIMARY KEY (
	"U_CD"
);

ALTER TABLE "UserInfo" ADD CONSTRAINT "FK_AUTHORITY_TO_UserInfo_1" FOREIGN KEY (
	"ROLE_CD"
)
REFERENCES "AUTHORITY" (
	"ROLE_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_UserInfo_TO_BOARD_1" FOREIGN KEY (
	"U_CD"
)
REFERENCES "UserInfo" (
	"U_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_REPLY_TO_BOARD_1" FOREIGN KEY (
	"REP_CD"
)
REFERENCES "REPLY" (
	"REP_CD"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "FK_ACCOUNT_INFO_TO_TRANSACTION_1" FOREIGN KEY (
	"ACC_NO"
)
REFERENCES "ACCOUNT_INFO" (
	"ACC_NO"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "FK_BANK_TYPE_TO_TRANSACTION_1" FOREIGN KEY (
	"BANK_CD"
)
REFERENCES "BANK_TYPE" (
	"BANK_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "FK_UserInfo_TO_ACCOUNT_INFO_1" FOREIGN KEY (
	"U_CD"
)
REFERENCES "UserInfo" (
	"U_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "FK_PRODUCT_TO_ACCOUNT_INFO_1" FOREIGN KEY (
	"PRO_CD"
)
REFERENCES "PRODUCT" (
	"PRO_CD"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_UserInfo_TO_REPLY_1" FOREIGN KEY (
	"U_CD"
)
REFERENCES "UserInfo" (
	"U_CD"
);

ALTER TABLE "RESTINPEACE" ADD CONSTRAINT "FK_UserInfo_TO_RESTINPEACE_1" FOREIGN KEY (
	"U_CD"
)
REFERENCES "UserInfo" (
	"U_CD"
);


--DROP TABLE "UserInfo";
--drop table BANK_TYPE;
--DROP TABLE "user_kko";
--DROP TABLE "BOARD";
--DROP TABLE "TRANSACTION";
--DROP TABLE "BANK_TYPE";
--DROP TABLE "ACCOUNT_INFO";
--DROP TABLE "PRODUCT";
--DROP TABLE "M_REPLY";
--DROP TABLE "AUTHORITY";
--DROP TABLE "OPENBANKING";
--DROP TABLE "FnA";
--DROP TABLE "U_REPLY";
--DROP TABLE "D_ADDRESS";



SELECT *
from BANK_TYPE;

SELECT *
from user;

Alter TABLE "UserInfo" rename to UserInfo;

commit;