CREATE TABLE "EMP" (
	"EMP_NO"	NUMBER		NOT NULL,
	"EMP_NM"	VARCHAR2(100)		NULL,
	"ADDR"	VARCHAR2(200)		NULL,
	"REG_DATETIME"	DATE		NULL,
	"DEPT_CD"	VARCHAR2(3)		NULL
);

CREATE TABLE "DEPT" (
	"DEPT_CD"	VARCHAR2(3)		NOT NULL,
	"DEPT_NM"	VARCHAR2(100)		NULL,
	"ADDR"	VARCHAR2(200)		NULL,
	"REG_DATETIME"	DATE		NULL
);

ALTER TABLE "EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY (
	"EMP_NO"
);

ALTER TABLE "DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY (
	"DEPT_CD"
);

ALTER TABLE "EMP" ADD CONSTRAINT "FK_DEPT_TO_EMP_1" FOREIGN KEY (
	"DEPT_CD"
)
REFERENCES "DEPT" (
	"DEPT_CD"
);

select *
from DEPT;

