CREATE TABLE "BANK_USER_INFO" (
   "USER_ID"   VARCHAR2(255)      PRIMARY KEY,
   "EMAIL"   VARCHAR2(255)      NOT NULL,
   "PASSWORD"   VARCHAR2(255)      NULL,
   "NAME"   VARCHAR2(255)      NULL,
   "BIRTH_DATE"   DATE      NULL,
   "PHONE_NUMBER"   VARCHAR2(20)      NULL,
   "ADDR"   VARCHAR2(255)      NULL,
   "ACCOUNT_LINK"   VARCHAR2(255)      NULL,
   "ADMIN_RIGHT"   NUMBER(1)      NULL
);

CREATE TABLE "SAVING_ACCOUNT" (
   "BANK_CD"   VARCHAR2(255)      NOT NULL,
   "AC_NUMBER"   VARCHAR2(255)      PRIMARY KEY,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "AC_PW"   VARCHAR2(4)      NULL,
   "AC_NAME"   VARCHAR2(255)      NULL,
   "BALANCE"   NUMBER(20)      NULL,
   "RATE"   NUMBER(5)      NULL,
   "AC_OP_DATE"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL,
   "USER_MEMO"   VARCHAR2(30)      NULL,
   "STATE"   NUMBER(1)      NULL
);

CREATE TABLE "DEPOSIT_ACCOUNT" (
   "BANK_CD"   VARCHAR2(255)      NULL,
   "AC_NUMBER"   VARCHAR2(20)      PRIMARY KEY,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "AC_PW"   VARCHAR2(4)      NULL,
   "AC_NAME"   VARCHAR2(255)      NULL,
   "BALANCE"   NUMBER(20)      NULL,
   "RATE"   NUMBER(5)      NULL,
   "AC_OP_DATE"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL,
   "AC_ED_DATE"   DATE      NULL,
    "TR_AC_NUMBER" VARCHAR2(20) NULL,
    "TR_TYPE" VARCHAR2(255) NULL,
    "TR_PAYMENT" NUMBER(20) NULL,
   "USER_MEMO"   VARCHAR2(30)      NULL
);

CREATE TABLE "QUERY_BOARD" (
   "POST_ID"   NUMBER(20)      NOT NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "TITLE"   VARCHAR2(255)      NULL,
   "CONTENTS"   VARCHAR2(4000)      NULL,
   "CREATE_TIME"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL,
   "IS_NOTICE"   NUMBER(1)      NULL,
    "VIEWS" NUMBER(20) NULL
);

CREATE TABLE "POST_COMMENT" (
   "COMMENT_ID"   NUMBER(20)      NOT NULL,
   "POST_ID"   NUMBER(20)      NOT NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "CONTENTS"   VARCHAR2(4000)      NULL,
   "CREATE_TIME"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL
);

CREATE TABLE "COMMENT_REPLY" (
   "COMMENT_REPLY_ID"   NUMBER(20)      NOT NULL,
   "COMMENT_ID"   NUMBER(20)      NOT NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "CONTENTS"   VARCHAR2(4000)      NULL,
   "CREATE_TIME"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL
);

CREATE TABLE "FINANCIAL_PRODUCT" (
   "PD_NUMBER"   NUMBER(20)      NOT NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "PD_NAME"   VARCHAR2(255)      NULL,
   "BALANCE"   NUMBER(20)      NULL,
   "AC_OP_DATE"   DATE      NULL
);

CREATE TABLE "TRANSACTION_HISTORY" (
   "TR_NUMBER"   NUMBER(20)      NOT NULL,
   "AC_NUMBER"   VARCHAR2(255)      NOT NULL,
   "TR_AC_NUMBER"   VARCHAR2(255)      NULL,
   "TR_NAME"   VARCHAR2(255)      NULL,
   "AMOUNT"   NUMBER(20)      NULL,
   "TR_TIME"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP      NULL
);

CREATE TABLE "FAVORITE_ACCOUNTS" (
   "FA_BANK_CD"   VARCHAR2(255)      NULL,
   "FA_AC_NUMBER"   NUMBER(20)      NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "FAVORITE_NAME"   VARCHAR2(255)      NULL
);

ALTER TABLE "BANK_USER_INFO" ADD CONSTRAINT "PK_USER_INFO" PRIMARY KEY (
   "USER_ID"
);

ALTER TABLE "SAVING_ACCOUNT" ADD CONSTRAINT "PK_SAVING_ACCOUNT" PRIMARY KEY (
   "BANK_CD",
   "AC_NUMBER"
);

ALTER TABLE "DEPOSIT_ACCOUNT" ADD CONSTRAINT "PK_DEPOSIT_ACCOUNT" PRIMARY KEY (
   "BANK_CD",
   "AC_NUMBER"
);

ALTER TABLE "QUERY_BOARD" ADD CONSTRAINT "PK_QUERY_BOARD" PRIMARY KEY (
   "POST_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
   "COMMENT_ID"
);

ALTER TABLE "COMMENT_REPLY" ADD CONSTRAINT "PK_COMMENT_REPLY" PRIMARY KEY (
   "COMMENT_REPLY_ID"
);

ALTER TABLE "FINANCIAL_PRODUCT" ADD CONSTRAINT "PK_FINANCIAL_PRODUCT" PRIMARY KEY (
   "PD_NUMBER"
);

ALTER TABLE "FAVORITE_ACCOUNTS" ADD CONSTRAINT "PK_FAVORITE_ACCOUNTS" PRIMARY KEY (
   "FA_BANK_CD",
   "FA_AC_NUMBER"
);