DROP TABLE UserInfo;

--CREATE SEQUENCE userinfo_u_cd_seq
--       INCREMENT BY 1
--       START WITH 100
----       MINVALUE 100
----       MAXVALUE 9999
--       NOCYCLE
--       NOCACHE
--       NOORDER;

--drop SEQUENCE userinfo_u_cd_seq;

CREATE TABLE UserInfo (
--	"U_CD"	       NUMBER		NOT NULL , 
	"U_ID"	VARCHAR2(100)		NOT NULL,
	"U_PW"	VARCHAR2(200)		NOT NULL,
	"U_NM"	VARCHAR2(200)		NOT NULL,
	"U_NUM"	VARCHAR2(200)		NOT NULL,
	"U_IDENTY"	NUMBER		NOT NULL,
	"U_EMAIL"	VARCHAR2(200)		NOT NULL,
	"SYS_JOIN"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"U_ROLE"	NUMBER(1)	DEFAULT 1	NOT NULL,
	"U_ADD"	VARCHAR2(255)		NULL,
       "U_STAT"	CHAR(1)	DEFAULT 'A'	NOT NULL
);

--COMMENT ON COLUMN "UserInfo"."U_CD" IS '회원식별번호';
--
--COMMENT ON COLUMN "UserInfo"."U_STAT" IS 'a가 액티브/u 언액티브';

DROP TABLE "user_kko";

CREATE TABLE "user_kko" (
	"TOKEN"	VARCHAR(255)		NOT NULL primary key,
	"K_EMIAL"	VARCHAR(255)		NULL,
	"K_BIRTH"	VARCHAR(255)		NULL
);

--COMMENT ON COLUMN "user_kko"."TOKEN" IS 'api로 가져올 토큰';

DROP TABLE "BOARD";

CREATE SEQUENCE board_post_cd_seq
       INCREMENT BY 1
       START WITH 2300000
--       MINVALUE 100
--       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

drop sequence  board_post_cd_seq;

CREATE TABLE "BOARD" (
	"POST_CD"	NUMBER		NOT NULL primary key,
	"U_ID"	       VARCHAR2(100)		NOT NULL,
	"POST_TITLE"	VARCHAR2(500)		NULL,
	"POST_CONTENT"	CLOB		NULL,
	"POST_DATE"	TIMESTAMP	DEFAULT SYSDATE	NULL,
	"POST_STAT"	NUMBER		NOT NULL,
	"REP_CD"	NUMBER		NOT NULL
);

--COMMENT ON COLUMN "BOARD"."U_CD" IS '회원식별번호';

DROP TABLE "TRANSACTION";

CREATE TABLE "TRANSACTION" (
	"TRANS_NO"	VARCHAR(255)		NOT NULL,
	"ACC_NO"	VARCHAR2(100)		NOT NULL,
	"BANK_CD"	CHAR(2)		NOT NULL,
	"TRANS_INPUT"	VARCHAR(255)		NOT NULL,
	"RECIEVER"	VARCHAR(255)		NOT NULL,
	"TRAN_TYPE"	VARCHAR(255)		NOT NULL,
	"TRAN_DATE"	TIMESTAMP		NOT NULL,
	"TRAN_MN"	VARCHAR(255)		NULL,
	"TRAN_BAL"	VARCHAR(255)		NULL
);

DROP TABLE "BANK_TYPE";

CREATE TABLE "BANK_TYPE" (
	"BANK_CD"	CHAR(2)		NOT NULL primary key,
	"BANK_NM"	VARCHAR2(100)		NULL
);

--COMMENT ON COLUMN "BANK_TYPE"."BANK_NM" IS '유니크로 만들어야할 것?';

DROP TABLE "ACCOUNT_INFO";

CREATE TABLE "ACCOUNT_INFO" (
	"ACC_NO"	VARCHAR2(100)		NOT NULL primary key,
	"U_ID"	       NUMBER		NOT NULL,
	"PRO_CD"	VARCHAR(255)		NOT NULL,
	"BANK_CD"	CHAR(2)		NOT NULL,
	"ACC_NM"	VARCHAR2(100)		NOT NULL,
	"ACC_PW"	NUMBER		NOT NULL,
	"ACC_BAL"	NUMBER		NOT NULL,
	"ACC_DATE"	TIMESTAMP	NOT NULL,
	"ACC_CON"	CHAR(1)	DEFAULT 'N'	NULL
);

--COMMENT ON COLUMN "ACCOUNT_INFO"."U_CD" IS '회원식별번호';
--
--COMMENT ON COLUMN "ACCOUNT_INFO"."ACC_CON" IS 'Y/N으로 구분';

DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
	"PRO_CD"	VARCHAR(255)		NOT NULL,
	"PRO_NM"	VARCHAR(255)		NULL,
	"PRO_TYPE"	VARCHAR(255)		NULL
);

DROP TABLE "M_REPLY";

CREATE SEQUENCE m_reply_rep_cd_seq
       INCREMENT BY 1
       START WITH 2300000
--       MINVALUE 100
--       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

drop sequence  m_reply_rep_cd_seq;

CREATE TABLE "M_REPLY" (
	"REP_CD"	NUMBER		NOT NULL,
	"POST_CD"	NUMBER		NOT NULL,
	"U_ID"	       VARCHAR2(100)		NOT NULL,
	"REP_CONTENT"	VARCHAR2(1000)	DEFAULT '현재 문의량이 많아 답변이 지연되고 있습니다. 최대한 빠르게 응대하고 있사오니 잠시만 기다려주세요.'	NULL
);

--COMMENT ON COLUMN "M_REPLY"."U_CD" IS '회원식별번호';

--DROP TABLE "AUTHORITY";

--role_cd는 각 지정 숫자가 있을 것
--CREATE TABLE "AUTHORITY" (
--	"ROLE_CD"	INTEGER		NOT NULL,
--	"ROLE_NM"	VARCHAR2(100)		NULL
--);

--COMMENT ON COLUMN "AUTHORITY"."ROLE_NM" IS '관리자/멤버/에이스/프리미어';

DROP TABLE "OPENBANKING";


DROP TABLE "FnA";

CREATE TABLE "FnA" (
	"FnA_CD"	NUMBER		NOT NULL,
	"FnA_STAT"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"Field"	VARCHAR(255)		NULL,
	"Field2"	VARCHAR(255)		NULL
);

--COMMENT ON COLUMN "FnA"."FnA_STAT" IS 'n은 일반 b는 자주묻는 질문에 등록';

DROP TABLE "U_REPLY";

CREATE TABLE "U_REPLY" (
	"U_REPCD"	NUMBER		NOT NULL,
	"U_REPCONT"	CLOB		NULL
);

--DROP TABLE "D_ADDRESS";
--
--CREATE TABLE "D_ADDRESS" (
--	"U_ID"	       VARCHAR2(100)		NOT NULL,
--	"U_ZIP"	VARCHAR2(50)		NULL,
--	"U_ADD"	VARCHAR2(100)		NULL,
--	"U_D_ADD"	VARCHAR2(100)		NULL
--);

--COMMENT ON COLUMN "D_ADDRESS"."U_CD" IS '회원식별번호';

ALTER TABLE "UserInfo" ADD CONSTRAINT "PK_USERINFO" PRIMARY KEY (
	"U_ID"
);

ALTER TABLE "user_kko" ADD CONSTRAINT "PK_USER_KKO" PRIMARY KEY (
	"TOKEN"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"POST_CD"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "PK_TRANSACTION" PRIMARY KEY (
	"TRANS_NO",
	"ACC_NO"
);

ALTER TABLE "BANK_TYPE" ADD CONSTRAINT "PK_BANK_TYPE" PRIMARY KEY (
	"BANK_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "PK_ACCOUNT_INFO" PRIMARY KEY (
	"ACC_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_CD"
);

ALTER TABLE "M_REPLY" ADD CONSTRAINT "PK_M_REPLY" PRIMARY KEY (
	"REP_CD"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"ROLE_CD"
);

ALTER TABLE "FnA" ADD CONSTRAINT "PK_FNA" PRIMARY KEY (
	"FnA_CD"
);

ALTER TABLE "U_REPLY" ADD CONSTRAINT "PK_U_REPLY" PRIMARY KEY (
	"U_REPCD"
);

ALTER TABLE "D_ADDRESS" ADD CONSTRAINT "PK_D_ADDRESS" PRIMARY KEY (
	"U_ID"
);

ALTER TABLE "UserInfo" ADD CONSTRAINT "FK_AUTHORITY_TO_UserInfo_1" FOREIGN KEY (
	"ROLE_CD"
)
REFERENCES "AUTHORITY" (
	"ROLE_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_UserInfo_TO_BOARD_1" FOREIGN KEY (
	"U_ID"
)
REFERENCES "UserInfo" (
	"U_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_M_REPLY_TO_BOARD_1" FOREIGN KEY (
	"REP_CD"
)
REFERENCES "M_REPLY" (
	"REP_CD"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "FK_ACCOUNT_INFO_TO_TRANSACTION_1" FOREIGN KEY (
	"ACC_NO"
)
REFERENCES "ACCOUNT_INFO" (
	"ACC_NO"
);

ALTER TABLE "TRANSACTION" ADD CONSTRAINT "FK_BANK_TYPE_TO_TRANSACTION_1" FOREIGN KEY (
	"BANK_CD"
)
REFERENCES "BANK_TYPE" (
	"BANK_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "FK_UserInfo_TO_ACCOUNT_INFO_1" FOREIGN KEY (
	"U_ID"
)
REFERENCES "UserInfo" (
	"U_ID"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "FK_PRODUCT_TO_ACCOUNT_INFO_1" FOREIGN KEY (
	"PRO_CD"
)
REFERENCES "PRODUCT" (
	"PRO_CD"
);

ALTER TABLE "ACCOUNT_INFO" ADD CONSTRAINT "FK_BANK_TYPE_TO_ACCOUNT_INFO_1" FOREIGN KEY (
	"BANK_CD"
)
REFERENCES "BANK_TYPE" (
	"BANK_CD"
);

ALTER TABLE "M_REPLY" ADD CONSTRAINT "FK_BOARD_TO_M_REPLY_1" FOREIGN KEY (
	"POST_CD"
)
REFERENCES "BOARD" (
	"POST_CD"
);

ALTER TABLE "M_REPLY" ADD CONSTRAINT "FK_UserInfo_TO_M_REPLY_1" FOREIGN KEY (
	"U_ID"
)
REFERENCES "UserInfo" (
	"U_ID"
);

ALTER TABLE "D_ADDRESS" ADD CONSTRAINT "FK_UserInfo_TO_D_ADDRESS_1" FOREIGN KEY (
	"U_ID"
)
REFERENCES "UserInfo" (
	"U_ID"
);


--제약조건 있는 테이블 강제 삭제하기
--drop table [테이블명] cascade constraints;

commit;